# TCL File Generated by Component Editor 18.1
# Sun Apr 21 21:11:00 CDT 2019
# DO NOT MODIFY


# 
# VGA_Component_Core "VGA Component Core" v4.20
#  2019.04.21.21:11:00
# This module communicates with graphics on software side and delivers it to VGA side 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module VGA_Component_Core
# 
set_module_property DESCRIPTION "This module communicates with graphics on software side and delivers it to VGA side "
set_module_property NAME VGA_Component_Core
set_module_property VERSION 4.20
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "ECE 385 Custom IPs"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "VGA Component Core"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_vga_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_vga_interface.sv SYSTEM_VERILOG PATH avalon_vga_interface.sv TOP_LEVEL_FILE
add_fileset_file VGA_controller.sv SYSTEM_VERILOG PATH VGA_controller.sv
add_fileset_file vga_clk.v VERILOG PATH vga_clk.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avalon_vga_interface
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_vga_interface.sv SYSTEM_VERILOG PATH avalon_vga_interface.sv
add_fileset_file VGA_controller.sv SYSTEM_VERILOG PATH VGA_controller.sv
add_fileset_file vga_clk.v VERILOG PATH vga_clk.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 50000000
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK clk Input 1


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock CLK
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET RESET reset Input 1


# 
# connection point VGA_Slave
# 
add_interface VGA_Slave avalon end
set_interface_property VGA_Slave addressAlignment DYNAMIC
set_interface_property VGA_Slave addressUnits WORDS
set_interface_property VGA_Slave associatedClock CLK
set_interface_property VGA_Slave associatedReset RESET
set_interface_property VGA_Slave burstOnBurstBoundariesOnly false
set_interface_property VGA_Slave explicitAddressSpan 0
set_interface_property VGA_Slave holdTime 0
set_interface_property VGA_Slave isMemoryDevice false
set_interface_property VGA_Slave isNonVolatileStorage false
set_interface_property VGA_Slave linewrapBursts false
set_interface_property VGA_Slave maximumPendingReadTransactions 0
set_interface_property VGA_Slave maximumPendingWriteTransactions 0
set_interface_property VGA_Slave printableDevice false
set_interface_property VGA_Slave readLatency 0
set_interface_property VGA_Slave readWaitStates 0
set_interface_property VGA_Slave readWaitTime 0
set_interface_property VGA_Slave setupTime 0
set_interface_property VGA_Slave timingUnits Cycles
set_interface_property VGA_Slave writeWaitTime 0
set_interface_property VGA_Slave ENABLED true
set_interface_property VGA_Slave EXPORT_OF ""
set_interface_property VGA_Slave PORT_NAME_MAP ""
set_interface_property VGA_Slave CMSIS_SVD_VARIABLES ""
set_interface_property VGA_Slave SVD_ADDRESS_GROUP ""

add_interface_port VGA_Slave AVL_ADDR address Input 3
add_interface_port VGA_Slave AVL_BYTE_EN byteenable Input 4
add_interface_port VGA_Slave AVL_CS chipselect Input 1
add_interface_port VGA_Slave AVL_WRITE write Input 1
add_interface_port VGA_Slave AVL_WRITEDATA writedata Input 32
add_interface_port VGA_Slave AVL_READ read Input 1
add_interface_port VGA_Slave AVL_READDATA readdata Output 32
set_interface_assignment VGA_Slave embeddedsw.configuration.isFlash 0
set_interface_assignment VGA_Slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment VGA_Slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment VGA_Slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point Export_Data
# 
add_interface Export_Data conduit end
set_interface_property Export_Data associatedClock CLK
set_interface_property Export_Data associatedReset ""
set_interface_property Export_Data ENABLED true
set_interface_property Export_Data EXPORT_OF ""
set_interface_property Export_Data PORT_NAME_MAP ""
set_interface_property Export_Data CMSIS_SVD_VARIABLES ""
set_interface_property Export_Data SVD_ADDRESS_GROUP ""

add_interface_port Export_Data EXPORT_DATA new_signal Output 32

